local function apply_highlights()
  local hl = vim.api.nvim_set_hl

  hl(0, "Normal", { bg = "NONE" })
  hl(0, "NormalNC", { bg = "NONE" })
  hl(0, "SignColumn", { bg = "NONE" })
  hl(0, "EndOfBuffer", { bg = "NONE" })
  hl(0, "LineNr", { bg = "NONE" })
  hl(0, "CursorLineNr", { bg = "NONE" })
  hl(0, "FoldColumn", { bg = "NONE" })
  hl(0, "NormalFloat", { bg = "NONE" })
  hl(0, "FloatBorder", { bg = "NONE", fg = "#6272A4" })

  hl(0, "Pmenu", { bg = "#3E4452", fg = "#ABB2BF" })
  hl(0, "PmenuSel", { bg = "#528BFF", fg = "#FFFFFF", bold = true })
  hl(0, "PmenuSbar", { bg = "#5C6370" })
  hl(0, "PmenuThumb", { bg = "#ABB2BF" })

  hl(0, "CmpItemMenu", { fg = "#C678DD", italic = true })
  hl(0, "CmpItemAbbr", { fg = "#ABB2BF" })
  hl(0, "CmpItemAbbrMatch", { fg = "#61AFEF", bold = true })
  hl(0, "CmpItemAbbrMatchFuzzy", { fg = "#61AFEF", bold = true })
  hl(0, "CmpItemKindText", { fg = "#ABB2BF" })
  hl(0, "CmpItemKindMethod", { fg = "#C678DD" })
  hl(0, "CmpItemKindFunction", { fg = "#C678DD" })
  hl(0, "CmpItemKindConstructor", { fg = "#E06C75" })
  hl(0, "CmpItemKindField", { fg = "#E5C07B" })
  hl(0, "CmpItemKindVariable", { fg = "#E06C75" })
  hl(0, "CmpItemKindClass", { fg = "#E5C07B" })
  hl(0, "CmpItemKindInterface", { fg = "#E5C07B" })
  hl(0, "CmpItemKindModule", { fg = "#61AFEF" })
  hl(0, "CmpItemKindProperty", { fg = "#E06C75" })
  hl(0, "CmpItemKindUnit", { fg = "#98C379" })
  hl(0, "CmpItemKindValue", { fg = "#98C379" })
  hl(0, "CmpItemKindEnum", { fg = "#E5C07B" })
  hl(0, "CmpItemKindKeyword", { fg = "#C678DD" })
  hl(0, "CmpItemKindSnippet", { fg = "#56B6C2" })
  hl(0, "CmpItemKindColor", { fg = "#98C379" })
  hl(0, "CmpItemKindFile", { fg = "#ABB2BF" })
  hl(0, "CmpItemKindReference", { fg = "#ABB2BF" })
  hl(0, "CmpItemKindFolder", { fg = "#61AFEF" })
  hl(0, "CmpItemKindEnumMember", { fg = "#98C379" })
  hl(0, "CmpItemKindConstant", { fg = "#E5C07B" })
  hl(0, "CmpItemKindStruct", { fg = "#E5C07B" })
  hl(0, "CmpItemKindEvent", { fg = "#C678DD" })
  hl(0, "CmpItemKindOperator", { fg = "#56B6C2" })
  hl(0, "CmpItemKindTypeParameter", { fg = "#E5C07B" })

  hl(0, "DiffAdd", { bg = "#2D3F34" })
  hl(0, "DiffDelete", { bg = "#4A2D2D" })
  hl(0, "DiffChange", { bg = "#2D324A" })
  hl(0, "DiffText", { bg = "#3E5C4A", bold = true })
end

apply_highlights()

vim.api.nvim_create_autocmd("ColorScheme", {
  group = vim.api.nvim_create_augroup("config.theme", { clear = true }),
  callback = apply_highlights,
})
